// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnuzvcwusafxoaehrbzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxudXp2Y3d1c2FmeG9hZWhyYnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MDkwNDksImV4cCI6MjA1MDM4NTA0OX0.S39bknNxBx6pDZX-J_S7ziuway_roLRVaAveb1SOLXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);